blog/urls.py
from django.urls import path

from website.views import index
from blog.views import blog_single,blog_view,test



app_name='blog'


urlpatterns = [
path('',blog_view,name='index'),
path('<int:pid>',blog_single,name='blog_single'),

path('test/',test,name='blog_details'),
]

mysite/urls.py
from django.contrib import admin
#modular mapping
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from website.views import blog
0
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
    path('blog/',include('blog.urls')),
   
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path,re_path
from  website.views import about, http_test,json_response,index,contact,template,blog,service

app_name='website'

urlpatterns = [
# path('blog/',http_test),
path('blog/json/',json_response),
path('',index , name='index'),
path('about/' ,about,name='about'),
path('class/',service,name='service'),
path('blogfa/',blog,name='blog'),
# re_path(r'^[a-c]/',about),
path('contact/',contact),
path('template/',template),
path('contact',contact,name='contact'),
]

blog/models.py
import re
from django.db import models
from django.contrib.auth.models import User





#Cathegory Model
class Category(models.Model):
    name = models.CharField(max_length=50,null=True)

    def __str__(self):
        return self.name
  
        


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField(max_length=100000000)
    image = models.ImageField(upload_to='blog/',default='blog/default.jpg')
    #tags
    category =models.ManyToManyField(Category)
    author = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    counted_views = models.IntegerField(default=0) #defaulr=0
    status = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now=True)
    class Meta:
        ordering= ['created_date']
        verbose_name = 'postBlog'
        verbose_name_plural = 'postBlog'  


    def count_posts_of(user):
        return Post.objects.filter(author=user).count()

    def __str__(self) -> str:
        return f"{self.id}-{self.title}"

    def snippets(self):
        return self.content[:100] + '...'  
   
   
    



# craete Contact model
class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)  

    class Meta:
        ordering = ['created_date']
    def __str__(self):
        return self.name


class UserProfile(models.Model):
    address = models.CharField(max_length=255,blank=True,null=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    about = models.TextField(max_length=500,blank=True)     

website/models.py
from django.db import models

# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)


    

blog/views.py
from datetime import date
from email.mime import audio
from gc import get_objects
import imp
from multiprocessing.spawn import import_main_path
import re
from django.shortcuts import get_object_or_404, render
from datetime import date
from blog.models import Post,UserProfile,User,Category

# Create your views here.
def blog_view(request):
    # content={'title':'why mathemathic??','author':'noora habibi','date_publish':date.today()}
    category=Category.objects.all()
    
    #get len of category list
    lst=[]
    for item in category:
        lst.append(item)
    len_lst_category= len(lst)   
        
    posts=Post.objects.filter(status=True)
    content={"posts": posts,'category':category,'category_count':len_lst_category}
    return render(request,'blog/blog.html',context=content)

def blog_single(request,pid):
    
    post=get_object_or_404(Post,id=pid,status=True)
    category=Category.objects.all()
    
    userprofile=UserProfile.objects.all()
    content={'post':post,'userprofile':userprofile,'category':category}
    return render(request,'blog/blog-item.html',context=content)

def test(request):
    
    
    return render(request,'blog/test.html') 

website/views.py
from django.shortcuts import render
# Create your views here.
import re
from django.http import HttpResponse,JsonResponse

def http_test(request):
    return HttpResponse("kavehmollaei")

def json_response(request):
    return JsonResponse({'name':'kaveh'})

def about(request):
    return render(request,'website/about.html')    

def blog(request):
    return render(request,'blog/blog.html')


def index(request):
    return render(request,'website/index.html')


def contact(request):
    return render(request,'website/contact.html')

def service(request):
    return render(request,'website/service.html')

def template(request):
    template_tag={"name":"kavehmollaei"}
    return render(request,'website/index.html',context=template_tag)

templates/blog/blog-item.html
{% extends 'website/base.html'%}
{% load static %}
{% load blog_tags %}


{% block content %}

        <!-- Start Header Section -->
        <div class="page-header">
            <div class="overlay">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1>{{post.title}}</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Header Section -->
        
        
        
        
        
        <!-- Start Blog Page Section -->
        <div class="container">
            <div class="row">
                
                <!-- Start Blog Body Section -->
                <div class="col-md-8 blog-body">
                    
                    <!-- Start Blog post -->
                    <div class="single-blog-post">
                        <div class="post-img">
                            <img src="{% static 'images/blog/blog-02.jpg' %}" class="img-responsive" alt="Blog image">
                        </div>
                        <h1 class="post-title"><a href="#">{{post.title}}</a></h1>
                        
                        <div class="post-meta">
                            <ul class=" pull-left">
                                <li><i class="fa fa-clock-o"></i>{{post.published_date|date:"D d m Y"}}</li>
                                <li><i class="fa fa-user"></i><a href="#">{{post.author.get_full_name}}</a></li>
                             
                              
                                <li><i class="fa fa-comments"></i><a href="#">4 Comments</a></li>
                            </ul>
                            <ul class="pull-right">
                                <!-- <li>font-size<i class="fa fa-minus-circle"></i><i class="fa fa-plus-circle"></i></li> -->
                                <!-- <li><a href="#">Print</a></li> -->
                                <li><a href="#">{{post.author.email}}</a></li>
                            </ul>
                        </div>
                        
                        
                        <p class="post-content">{{post.content}}</p>
                        
                        <div class="item-content-footer">
                            <ul>
                                <li>Read 286 times</li>
                                <li class="rating">
                                    Rate this item 
                                    <span class="active"><i class="fa fa-star-o"></i></span>
                                    <span class="active"><i class="fa fa-star-o"></i></span>
                                    <span class="active"><i class="fa fa-star-o"></i></span>
                                    <span><i class="fa fa-star-o"></i></span>
                                    <span><i class="fa fa-star-o"></i></span>
                                </li>
                            </ul>
                        </div>
                        
                    </div>
                    <!-- End Blog Post -->
                    
                    
                    <!-- Start Blog Author Section -->
                    <div class="blog-author">
                        <h3>About Me</h3>
                        <div class="media">
                            <div class="media-left">
                                <a href="#">
                                    <img class="media-object" src="{% static 'images/user.png' %}" alt="...">
                                </a>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading"><a href="#">{{post.author.get_full_name}}</a></h4>
                                {% for item in userprofile %}
                                 {% if post.author.username == item.user.username %}                             
                                <p> {{item.about}}</p>
                                {% endif %}
                               {% endfor %}
                            </div>
                        </div>
                    </div>
                    <!-- End Blog Author Section -->
                    
                    <!-- Start Comments Section -->
                    <div id="comments">
                        <h2 class="comments-title">4 comments</h2>
                        <ol class="comments-list">
                            <li>
                                <div class="comment-box clearfix">
                                    <div class="avatar"><img alt="" src=" {% static 'images/user-2.png' %}"></div>
                                    <div class="comment-content">
                                        <div class="comment-meta">
                                            <span class="comment-by">fghfghjfghj</span>
                                            <span class="reply-link pull-right"><a href="#">Comment Link</a></span>
                                        </div>
                                        <span class="comment-date">Sunday, 15 February 2015 at 20:39</span>
                                        <p>Dette er en besked</p>
                                    </div>
                                </div>
     
                                <ul>
                                    <li>
                                        <div class="comment-box clearfix">
                                            <div class="avatar"><img alt="" src="{% static 'images/user-2.png' %}"></div>
                                            <div class="comment-content">
                                                <div class="comment-meta">
                                                    <span class="comment-by">sdfaasdfb</span>
                                                    <span class="reply-link pull-right"><a href="#">Comment Link</a></span>
                                                </div>
                                                <span class="comment-date">Sunday, 15 February 2015 20:39</span>
                                                <p>sdfadasdfawefasdf a</p>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </li>
  
                            <li>
                                <div class="comment-box clearfix">
                                    <div class="avatar"><img alt="" src="{% static 'images/user-2.png' %}"></div>
                                    <div class="comment-content">
                                        <div class="comment-meta">
                                            <span class="comment-by">sa</span>
                                            <span class="reply-link pull-right"><a href="#">Comment Link</a></span>
                                        </div>
                                        <span class="comment-date">Tuesday, 03 February 2015 06:41</span>
                                        <p>daaass</p>
                                    </div>
                                </div>
                                
                                <ul>
                                    <li>
                                        <div class="comment-box clearfix">
                                            <div class="avatar"><img alt="" src="{% static 'images/user-2.png' %}"></div>
                                            <div class="comment-content">
                                                <div class="comment-meta">
                                                    <span class="comment-by">xc zc</span>
                                                    <span class="reply-link pull-right"><a href="#">Comment Link</a></span>
                                                </div>
                                                <span class="comment-date">Wednesday, 10 December 2014 11:42</span>
                                                <p>fsfsfs</p>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </li>
 
                        </ol>
                        
                        <!-- Start Respond Form -->
                        <div id="respond">
                            <h2 class="respond-title">Leave a comment</h2>
                            <span class="form-caution">Make sure you enter the (*) required information where indicated. HTML code is not allowed.</span>
                            <form action="#">
                                <div class="row">
                                    <div class="col-md-4">
                                        <label for="author">Name<span class="required">*</span></label>
                                        <input id="author" name="author" type="text" size="30" aria-required="true">
                                    </div>
                                    <div class="col-md-4">
                                        <label for="email">Email<span class="required">*</span></label>
                                        <input id="email" name="author" type="text" size="30" aria-required="true">
                                    </div>
                                    <div class="col-md-4">
                                        <label for="url">Website<span class="required">*</span></label>
                                        <input id="url" name="url" type="text" size="30" aria-required="true">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <label for="comment">Add Your Comment</label>
                                        <textarea id="comment" name="comment" cols="45" rows="8" aria-required="true"></textarea>
                                        <input name="submit" type="submit" id="submit" class="btn btn-primary" value="Submit Comment">
                                    </div>
                                </div>
                            </form>
                        </div>
                        <!-- End Respond Form -->

                    </div>
                    <!-- End Comments Section -->
                    
                    
                    
                    
                </div>
                <!-- End Blog Body Section -->
                
                <!-- Start Sidebar Section -->
                <div class="col-md-4 sidebar right-sidebar">
                    
                    
                    <!-- Start Flickr Widget -->
                    {% include 'blog/blog-tabligh.html' %}
                  
                    <!-- End Flickr Widget -->
                    
                    
                    <!-- Start Recent Post Widget -->
                    {% include 'blog/recentpost.html'%}
                    <!-- End Recent Post Widget -->
                    
                    
                    <!-- Start Blog categories widget -->
                    <div class="widget widget-categories">
                        
                        <div class="section-heading-2">
                            <h3 class="section-title">
                                <span>Blog Posts</span>
                                {{posts}}
                            </h3>
                        </div>
                        
                        <ul>
                           
                                {% for item in category %}
                            
    
                                
                                <li>
                                    <i class="fa fa-angle-double-right"></i>
                                    <a href="#">{{item.name}}</a>
                                    <a href="#" class="cat-counter">(4)</a>
                                </li>
                                {% endfor%}
                                
                            </ul>
                           
                    
                        
                    </div>
                    <!-- End Blog categories widget -->
                    
                    
                    <!-- Start Tag Cloud Widget -->
                    <div class="widget widget-tags">
                        
                        <div class="section-heading-2">
                            <h3 class="section-title">
                                <span>Popular Tags</span>
                            </h3>
                        </div>
                        
                        <div class="tagcloud">
                            <a href="#">Charity</a>
							<a href="#">Children</a>
							<a href="#">Education</a>
							<a href="#">Elderly</a>
							<a href="#">Humanity</a>
							<a href="#">Women Rights</a>
				        </div>
                        
                    </div>
                    <!-- End Tag Cloud Widget -->
                    
                    
                    
                </div>
                <!-- End Sidebar Section -->
                
            </div>
        </div>
        <!-- End Blog Page Section -->
        {% endblock%}

templates/blog/blog-tabligh.html
{% load static %}

<!-- Start Flickr Widget -->

  <div class="widget flickr-widget">
                        
    <div class="section-heading-2">
        <h3 class="section-title">
            <span>Services</span>
        </h3>
    </div>
    
   <p>    آموزش زبان برنامه نویسی و برگزاری دوره های آموزسی برای نوجوانان </p> <ul class="flickr-list">
        <li>
            <a href="{% static 'images/flickr/8.jpg'%}" data-lightbox="picture-1">
                <img src="{% static 'images/flickr/8.jpg'%}" alt="" class="img-responsive">
            </a>
        </li>
        <li>
            <a href="{% static 'images/flickr/7.jpg'%}" data-lightbox="picture-2">
                <img src="{% static 'images/flickr/7.jpg'%}" alt="" class="img-responsive">
            </a>
        </li>
        <li>
            <a href="{% static 'images/flickr/6.jpg'%}" data-lightbox="picture-3">
                <img src="{% static 'images/flickr/6.jpg'%}" alt="" class="img-responsive">
            </a>
        </li>
        <li>
            <a href="{% static 'images/flickr/5.jpg'%}" data-lightbox="picture-4">
                <img src="{% static 'images/flickr/5.jpg'%}" alt="" class="img-responsive">
            </a>
        </li>
        <li>
            <a href="{% static 'images/flickr/4.jpg'%}" data-lightbox="picture-5">
                <img src="{% static 'images/flickr/4.jpg'%}" alt="" class="img-responsive">
            </a>
        </li>
        <li>
            <a href="{% static 'images/flickr/3.jpg' %}" data-lightbox="picture-6">
                <img src="{% static 'images/flickr/3.jpg' %}" alt="" class="img-responsive">
            </a>
        </li>
        <li>
            <a href="{% static 'images/flickr/2.jpg' %}" data-lightbox="picture-7">
                <img src="{% static 'images/flickr/2.jpg' %}" alt="" class="img-responsive">
            </a>
        </li>
        <li>
            <a href="{% static 'images/flickr/1.jpg' %}" data-lightbox="picture-8">
                <img src="{% static 'images/flickr/1.jpg' %}" alt="" class="img-responsive">
            </a>
        </li>
    </ul>
</div>
<!-- End Flickr Widget -->

templates/blog/blog.html
{% extends 'website/base.html'%} 
{% load static %}
{% load blog_tags %}
{% block content %}

<!-- Start Header Section -->
<div class="page-header">
  <div class="overlay">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1>Blog</h1>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- End Header Section -->

<!-- Start Blog Page Section -->
<div class="container">
  <div class="row">
    <!-- Start Blog Body Section -->
    <div class="col-md-8 blog-body">
      {% for post in posts %}
      <!-- Start Blog post -->
      <div class="blog-post">
        <div class="post-img">
          <img
            src="{{post.image.url}}"
            class="img-responsive"
            alt="Blog image"
          />
        </div>
        <h1 class="post-title">
          <a href="{% url 'blog:blog_single' pid=post.id %}">{{post.title}}</a>
        </h1>

        <ul class="post-meta">
          <li><i class="fa fa-clock-o"></i>{{p}}</li>
          <li>
            <i class="fa fa-user"></i
            ><a href="#">{{post.author.get_full_name}}</a>
          </li>

          <li>
            <i class="fa fa-tags"></i><a href="#">{{post.counted_views}}</a>
          </li>
          <li><i class="fa fa-comments"></i><a href="#">4 Comments</a></li>
        </ul>
        {% for cat in post.category.all%}
        <span style="color: burlywood;" class="fa fa-tags"> {{cat.name}} </span>
        {% endfor %}
        <br />

        <p class="post-content">{{post.content|truncatechars:100}}</p>
        <a
          href="{% url 'blog:blog_single' pid=post.id %}"
          class="btn btn-primary readmore"
          >Read more...<i class="fa fa-angle-right"></i
        ></a>
      </div>
      {% endfor %}
      <!-- End Blog Post -->
      <!--
                    Start Blog post
                    <div class="blog-post">
                        <div class="post-img">
                            <img src="{% static 'images/blog/blog-02.jpg' %}" class="img-responsive" alt="Blog image">
                        </div>
                        <h1 class="post-title"><a href="#">Quisque cursus metus vitae pharetra auctor sem massa</a></h1>
                        
                        <ul class="post-meta">
							<li><i class="fa fa-clock-o"></i>{{date_publish}}</li>
							<li><i class="fa fa-user"></i><a href="#">{{author}}</a></li>
							<li><i class="fa fa-file"></i><a href="#">Blog</a></li>
							<li><i class="fa fa-tags"></i><a href="#">Elderly</a> <a href="#">Education</a></li>
							<li><i class="fa fa-comments"></i><a href="#">1 Comments</a></li>
						</ul>
                        
                        <p class="post-content">Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi lacinia molestie dui. Praesent blandit dolor. Sed non quam. In vel mi sit amet augue congue elementum. Morbi in ipsum sit amet pede facilisis laoreet. Donec lacus nunc, viverra nec, blandit vel, egestas et, augue. Vestibulum tincidunt malesuada tellus. Ut ultrices ultrices enim. Curabitur sit amet mauris. Morbi in dui quis est pulvinar ullamcorper.</p>
                        <a href="#" class="btn btn-primary readmore">Read more...<i class="fa fa-angle-right"></i></a>
                    </div>
                    End Blog post -->

      <div class="widget widget-categories">
        <div class="section-heading-2">
          <h3 class="section-title">
            <span>Blog Categories</span>
          </h3>
        </div>

        <ul>
          {% for item in category %}

          <li>
            <i class="fa fa-angle-double-right"></i>
            <a href="#">{{item.name}}</a>
            <a href="#" class="cat-counter">(4)</a>
          </li>
          {% endfor%}
        </ul>
      </div>
      <!-- Start Pagination -->
      <nav>
        <ul class="pagination">
          <li class="disabled"><a href="#" aria-label="Start">Start</a></li>
          <li class="disabled"><a href="#" aria-label="Previous">Prev</a></li>
          <li class="active"><a href="#">1</a></li>
          <li><a href="#">2</a></li>
          <li><a href="#">Next</a></li>
          <li><a href="#">End</a></li>
        </ul>
      </nav>
      <!-- End Pagination -->
    </div>
    <!-- End Blog Body Section -->

    <!-- Start Sidebar Section -->
    <div class="col-md-4 sidebar right-sidebar">
      <!-- Start Flickr Widget -->
      {% include 'blog/blog-tabligh.html' %}
      <!-- End Flickr Widget -->

      <!-- Start Recent Post Widget -->
      {% latestposts %}
      <!-- End Recent Post Widget -->
    
      <!-- Start Blog categories widget -->
      <div class="widget widget-categories">
        <div class="section-heading-2">
          <h3 class="section-title">
            <span>Blog Categories Count</span>
            <i style="color: royalblue;" class="fa fa-angle-double-right">  {{category_count}} </i>
            
          </h3>
          
        </div>
        
           
        <ul>
          {% for item in category %}
          <li>
            <i class="fa fa-angle-double-right"></i>
            <a href="#">{{item.name}}</a>
            <a href="#" class="cat-counter">3</a>
          </li>
          {% endfor%}
        </ul>
      </div>

      <!-- End Blog categories widget -->

      <!-- Start Tag Cloud Widget -->
      <div class="widget widget-tags">
        <div class="section-heading-2">
          <h3 class="section-title">
            <span>Popular Tags</span>
          </h3>
        </div>

        <div class="tagcloud">
          <a href="#"></a>
          <a href="#">Children</a>
          <a href="#">Education</a>
          <a href="#">Elderly</a>
          <a href="#">Humanity</a>
          <a href="#">Women Rights</a>
        </div>
      </div>
      <!-- End Tag Cloud Widget -->
    </div>
    <!-- End Sidebar Section -->
  </div>
</div>
<!-- End Blog Page Section -->

{% endblock %}

templates/blog/popularpost.html
<u>
    {% for post in posts %}
    <li> {{post.title}}  </li>
    {% endfor%}

    </ul>

templates/blog/recentpost.html
{% load static %}

<div class="widget widget-recent-post">
                        
    <div class="section-heading-2">
        <h3 class="section-title">
            <span>Recent Posts</span>
        </h3>
    </div>
                {% for post in posts %}
    <div class="media">
        <div class="media-left">
            <a href="#">
                <img class="media-object" src="{% static 'images/recent-post/post-02.jpg' %}" alt="...">
            </a>
        </div>
        <div class="media-body">
            <h4 class="media-heading"><a href="#">{{post.title}}</a></h4>
            <ul>
                <li><a href="#">{{post.author.get_full_name}}</a></li>
                <li>{{post.published_date|date:'d M Y'}}</li>
            </ul>
        </div>
    </div>
    {% endfor %}
 
    
    
</div>

templates/blog/test.html
{% load blog_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>This is test page fo blog app</title>
</head>



<body>
    <div>
        <p>
          
{% posts as total  %}
            {% for post in total %}
            <p>{{ post.content|snippet:10 }}</p>

            {% endfor %}
        </p>


    </div>

    <div>

        {% popularposts %}
    </div>
</body>
</html>